{% set name = "multiprocessing-logging" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jruere/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 322c0750ee39ec842eea504f88f54a2764961d04aba78b5dea801d51bce9bbcb

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - multiprocessing_logging
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jruere/multiprocessing-logging
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python tooling to help logging work with multiprocessing
  dev_url: https://github.com/jruere/multiprocessing-logging

extra:
  recipe-maintainers:
    - phlya
    - jordan-heemskerk
