{% set name = "multiprocessing-logging" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jruere/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 47f68007ceca4d385166f7214e957148e0262814c64bac892ebe5f2da7593fa3

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - python =2.7.* | >=3.6
    - pip
  run:
    - python =2.7.* | >=3.6

test:
  imports:
    - multiprocessing_logging
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jruere/multiprocessing-logging
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python tooling to help logging work with multiprocessing
  dev_url: https://github.com/jruere/multiprocessing-logging

extra:
  recipe-maintainers:
    - phlya
    - jordan-heemskerk
